from __future__ import annotations

from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException

import app.deps as deps
from app.schemas import ApiResponse
from app.services.ai import simple_ai_reply
from app.services.documents import extract_text, resolve_local_path_from_files_url
from app.services.rag import chunk_text, retrieve_embeddings, retrieve_tfidf

router = APIRouter(prefix="/doc", tags=["Doc"])


@router.post("/interpret", response_model=ApiResponse)
def doc_interpret(payload: Dict[str, Any], user=Depends(deps.get_current_user)):
    """Interpret a document that was uploaded to this service.

    Frontend contract:
    - POST /api/doc/interpret
    - JSON fields:
      - required: fileUrl (must be /files/...)
      - optional: fileName, fileSize, fileMime, question, conversationId

    Notes:
    - This endpoint uses a lightweight local RAG (TF-IDF retrieval) to keep the answer grounded.
    - The final answer is generated by qwen3-max via simple_ai_reply().
    """

    file_url = payload.get("fileUrl")
    if not file_url or not isinstance(file_url, str):
        raise HTTPException(status_code=400, detail="fileUrl required")

    fp = resolve_local_path_from_files_url(file_url)

    file_mime: Optional[str] = payload.get("fileMime")
    question: str = (payload.get("question") or "").strip()

    # 1) extract text
    text, meta = extract_text(fp, mime=file_mime)
    if not text.strip():
        raise HTTPException(status_code=422, detail="document has no extractable text")

    # 2) rag retrieve
    # If user doesn't ask, default to summary.
    effective_query = question or "请用中文总结这份文档的核心内容，并列出 5 条要点。"
    chunks = chunk_text(text, chunk_chars=1200, overlap=150)
    # Prefer Qwen embeddings retrieval; fall back to local TF-IDF if embeddings call fails.
    try:
        retrieved = retrieve_embeddings(effective_query, chunks, top_k=5, model="text-embedding-v4")
        rag_method = "text-embedding-v4"
    except Exception:
        retrieved = retrieve_tfidf(effective_query, chunks, top_k=5)
        rag_method = "tfidf"

    context_lines = []
    for r in retrieved:
        context_lines.append(f"[chunk#{r.index} score={r.score:.3f}]\n{r.text}")
    context = "\n\n".join(context_lines)

    prompt = (
        "你将阅读一份文档的部分片段（从用户上传的文件中抽取并检索得到）。\n"
        "请严格基于这些片段回答，避免凭空编造。\n\n"
        f"用户问题：{effective_query}\n\n"
        "文档片段：\n"
        f"{context}\n\n"
        "请输出：\n"
        "1) 一段简短回答\n"
        "2) 5 条要点（用 - 列表）\n"
    )

    answer = simple_ai_reply(prompt, history=None)

    return ApiResponse(
        data={
            "conversationId": payload.get("conversationId"),
            "answer": answer,
            "meta": {
                **(meta or {}),
                "fileUrl": file_url,
                "fileName": payload.get("fileName"),
                "fileSize": payload.get("fileSize"),
                "fileMime": file_mime,
                "rag": {
                    "method": rag_method,
                    "chunks": len(chunks),
                    "topK": len(retrieved),
                    "used": [r.index for r in retrieved],
                },
                "model": "qwen3-max",
            },
        }
    )
